version: 0.2

phases:
  install:
    commands:
    - npm install
    - npm run module-install
  build:
    commands:
    - npm run package
  post_build:
    commands:
    - aws cloudformation package  --template-file ./products-service.yaml --s3-bucket shop-cf-resources --output-template-file products-service.pkg.yaml
artifacts:
  files:
  - products-service.pkg.yaml